### ISSUE TITLE
Citation of GBIF data

### ISSUE THREAD

**Issue by dnoesgaard** [cclubley/Assessing-invasion-dynamics#1]
Hi there.

The recommended way of citing data from GBIF obtained using rgbif::occ_search() is using a [derived dataset](https://www.gbif.org/citation-guidelines#thirdParty). Can you provide the file linked below? Then I can help create such a record.

https://github.com/cclubley/Assessing-invasion-dynamics/blob/74bf628ec82387f2503115b5223e2e0f083f46e5/Data/Downloading%20and%20cleaning%20open-source%20data.R#L181

Thanks!

**Comment by cclubley** [comment]
Hello. Please accept my apologies if GBIF data has been cited incorrectly in the manuscript. I had made efforts to try and cite correctly, and have included information on the dataset name, DOI, citation, rights and URL of the records obtained from GBIF in Supplementary table 4, although as the manuscript is still in the proof stage I am aware this content may not be available for you to view as of yet. 

I am happy to provide the file you have highlighted and will upload it to the data folder of this repository.

**Comment by dnoesgaard** [comment]
Thanks Charlotte!

I've now created a derived dataset record based on the data in the sheet you shared:

https://doi.org/10.15468/dd.n2y3vj

When cited, this will automatically reflect as a citation against the 93 parent datasets contributing records to the final dataset. If you could find a way to include this in the manuscript, it would be much appreciated!
